# Generated by Django 5.2.5 on 2025-09-04 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/', verbose_name='Foto de Perfil')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('DE', 'Documento de Identidad Extranjero')], max_length=2, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=50, unique=True, verbose_name='Número de Documento')),
                ('metodo_pago', models.CharField(choices=[('TC', 'Tarjeta de Crédito'), ('TD', 'Tarjeta Débito'), ('EF', 'Efectivo'), ('TB', 'Transferencia Bancaria'), ('ND', 'Nequi/Daviplata')], max_length=2, verbose_name='Método de Pago')),
                ('numero_cuenta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Cuenta')),
                ('modelo_marca_vehiculo', models.CharField(max_length=100, verbose_name='Modelo y Marca del Vehículo')),
                ('placa_vehiculo', models.CharField(max_length=10, verbose_name='Placa del Vehículo')),
                ('tipo_vehiculo', models.CharField(max_length=50, verbose_name='Tipo de Carro')),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('cuidado_especial', models.TextField(blank=True, null=True, verbose_name='Cuidado Especial del Vehículo')),
                ('acepta_terminos', models.BooleanField(default=False, verbose_name='Acepta Términos y Condiciones')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
