# Generated by Django 5.2.5 on 2025-09-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cuidado_especial',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='modelo_marca_vehiculo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='numero_cuenta',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='numero_documento',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='placa_vehiculo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tipo_documento',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tipo_vehiculo',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tipo_usuario',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('empleado', 'Empleado'), ('admin', 'Administrador')], default='cliente', max_length=10, verbose_name='Tipo de Usuario'),
        ),
    ]
