"""
Django settings for lavadero_project project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1_n)t=sqr=nt+9b%m1!oh=@w&9!w=22wf90r4pn=(!ttc&(&vc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lavadero_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lavadero_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'lavadero_bd',
        'USER': 'postgresql',
        'PASSWORD': 'CG8lfoD0xWboZq9s0nlzWuHvDjSTSwP1',

        'HOST': 'dpg-d2sqigemcj7s73ag8cgg-a.oregon-postgres.render.com',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

import os


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# lavadero_project/settings.py
LOGIN_REDIRECT_URL = '/dashboard/' # <-- ¡Cámbialo a la ruta de tu dashboard!
LOGOUT_REDIRECT_URL = '/'  # <-- Redirige al login después de logout



EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' 





# CONFIGURACIÓN PARA ENVÍO DE CORREOS EN PRODUCCIÓN (con Gmail)
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_PORT = 587
#EMAIL_USE_TLS = True  # Usar Transport Layer Security (es un protocolo de seguridad)
#EMAIL_HOST_USER = 'tu_correo@gmail.com'  # El correo desde el que se enviarán los emails
#EMAIL_HOST_PASSWORD = 'la_contraseña_de_16_caracteres'  # La contraseña de aplicación que generaste

#Reemplaza:

#tu_correo@gmail.com por la dirección de Gmail que estás usando.

#la_contraseña_de_16_caracteres por la contraseña de aplicación.
#pip install python-decouple

# Se debe crear un archivo .env en la raíz del proyecto (donde está manage.py) con las variables de entorno:
#  poner las variables de entorno en el archivo .env y no directamente en settings.py 
#  así evitamos exponer información sensible en el código fuente.

## .env
#EMAIL_USER=tu_correo@gmail.com
#EMAIL_PASSWORD=la_contraseña_de_16_caracteres
#